package app.android.damien.reef.model.aquariumdevices

data class Alkatronic(
    val aquarium_tank_id: Int,
    val batch_no: Int,
    val eligible_actions: List<EligibleAction>,
    val firmware_version: String,
    val friendly_name: String,
    val id: Int,
    val is_active: Int,
    val is_auto_update: Int,
    val is_beta_test: Boolean,
    val last_calibrate_a: Int,
    val last_calibrate_c: Int,
    val last_calibrate_d: Int,
    val last_calibrate_p: Int,
    val last_cloud_adv_record_time: Int,
    val last_cloud_adv_upload_time: Int,
    val last_online: Int,
    val last_reset_test_counter_time: Int,
    val lifetime_test_count: Int,
    val local_hour: Any,
    val local_ip_address: String,
    val local_minute: Any,
    val mac_address: Any,
    val mcu_status: Any,
    val mcu_version: Any,
    val next_firmware_version: String,
    val serial_number: String,
    val settings: Settings,
    val user_id: Int,
    val version: Int,
    val versions: Versions
)